// ---------------------------------------------------------------------------
// Tests for src/delivery/email.ts
// ---------------------------------------------------------------------------

import { describe, it, expect, mock, beforeEach, afterEach, spyOn } from "bun:test";

// ---------------------------------------------------------------------------
// Mocks -- must be declared before importing the module under test.
// We use a mutable config object so tests can override values without
// re-mocking the module (which leaks across test files in Bun).
// ---------------------------------------------------------------------------

const defaultConfig = {
  ANTHROPIC_API_KEY: "test-key",
  RESEND_API_KEY: "test-resend-key",
  EMAIL_TO: "test@example.com",
  TELEGRAM_BOT_TOKEN: "test-bot-token",
  TELEGRAM_CHAT_ID: "test-chat-id",
  EMBEDDING_API_KEY: "test-embedding-key",
  EMBEDDING_MODEL: "voyage-3",
  EMBEDDING_DIMENSIONS: 1024,
  DATABASE_URL: "postgresql://test:test@localhost:5432/test",
  PORT: 3000,
};

let currentConfig = { ...defaultConfig };

mock.module("../../../src/config.ts", () => ({
  getConfig: () => currentConfig,
}));

// Import AFTER mocks are set up
const {
  escapeHtml,
  markdownToHtml,
  wrapInHtmlTemplate,
  sendEmail,
  sendBriefEmail,
  sendAlertEmail,
} = await import("../../../src/delivery/email.ts");

type AlertEmailData = {
  itemTitle: string;
  urgency: string;
  reason: string;
  recommendedAction: string;
  url?: string | null;
};

// ---------------------------------------------------------------------------
// Pure function tests -- escapeHtml
// ---------------------------------------------------------------------------

describe("escapeHtml", () => {
  it("escapes &, <, >, and double quotes", () => {
    const input = 'Hello & "world" <script>alert(1)</script>';
    const result = escapeHtml(input);

    expect(result).toBe(
      "Hello &amp; &quot;world&quot; &lt;script&gt;alert(1)&lt;/script&gt;",
    );
  });

  it("handles empty string", () => {
    expect(escapeHtml("")).toBe("");
  });
});

// ---------------------------------------------------------------------------
// Pure function tests -- markdownToHtml
// ---------------------------------------------------------------------------

describe("markdownToHtml", () => {
  it("converts h1 headers", () => {
    const result = markdownToHtml("# Main Title");
    expect(result).toContain("<h1>Main Title</h1>");
  });

  it("converts h2 headers", () => {
    const result = markdownToHtml("## Section Title");
    expect(result).toContain("<h2>Section Title</h2>");
  });

  it("converts h3 headers", () => {
    const result = markdownToHtml("### Sub Section");
    expect(result).toContain("<h3>Sub Section</h3>");
  });

  it("converts bold and italic text", () => {
    const result = markdownToHtml("This is **bold** and *italic* text");
    expect(result).toContain("<strong>bold</strong>");
    expect(result).toContain("<em>italic</em>");
  });

  it("converts inline code", () => {
    const result = markdownToHtml("Use the `getConfig()` function");
    expect(result).toContain("<code>getConfig()</code>");
  });

  it("converts unordered lists", () => {
    const result = markdownToHtml("- Item one\n- Item two\n- Item three");
    expect(result).toContain("<ul>");
    expect(result).toContain("<li>Item one</li>");
    expect(result).toContain("<li>Item two</li>");
    expect(result).toContain("<li>Item three</li>");
    expect(result).toContain("</ul>");
  });

  it("converts links", () => {
    const result = markdownToHtml(
      "Visit [Example](https://example.com) for more",
    );
    expect(result).toContain('<a href="https://example.com">Example</a>');
  });
});

// ---------------------------------------------------------------------------
// Pure function tests -- wrapInHtmlTemplate
// ---------------------------------------------------------------------------

describe("wrapInHtmlTemplate", () => {
  it("includes subject in title, body in container, and has footer", () => {
    const result = wrapInHtmlTemplate("Test Subject", "<p>Body content</p>");

    // Subject in title tag
    expect(result).toContain("<title>Test Subject</title>");

    // Body in container
    expect(result).toContain('<div class="container">');
    expect(result).toContain("<p>Body content</p>");

    // Footer present
    expect(result).toContain("Generated by Coronagraph Intelligence Platform");
    expect(result).toContain('<div class="footer">');

    // Valid HTML structure
    expect(result).toContain("<!DOCTYPE html>");
    expect(result).toContain("</html>");
  });
});

// ---------------------------------------------------------------------------
// sendEmail tests
// ---------------------------------------------------------------------------

describe("sendEmail", () => {
  let fetchSpy: ReturnType<typeof spyOn>;

  beforeEach(() => {
    currentConfig = { ...defaultConfig };
    fetchSpy = spyOn(globalThis, "fetch").mockImplementation(() =>
      Promise.resolve(
        new Response(JSON.stringify({ id: "email-123" }), { status: 200 }),
      ),
    );
  });

  afterEach(() => {
    fetchSpy.mockRestore();
  });

  it("successful send returns success with id", async () => {
    const result = await sendEmail(
      "test@example.com",
      "Test Subject",
      "<p>Hello</p>",
    );

    expect(result.success).toBe(true);
    expect(result.id).toBe("email-123");
    expect(fetchSpy).toHaveBeenCalledTimes(1);

    const callArgs = fetchSpy.mock.calls[0];
    expect(callArgs[0]).toBe("https://api.resend.com/emails");
    const body = JSON.parse(callArgs[1]?.body as string);
    expect(body.to).toEqual(["test@example.com"]);
    expect(body.subject).toBe("Test Subject");
    expect(body.html).toBe("<p>Hello</p>");
  });

  it("returns error when no RESEND_API_KEY configured", async () => {
    currentConfig = {
      ...defaultConfig,
      RESEND_API_KEY: undefined as unknown as string,
    };

    const result = await sendEmail("to@test.com", "Subject", "<p>Hi</p>");

    expect(result.success).toBe(false);
    expect(result.error).toContain("RESEND_API_KEY");
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it("returns error on API error response", async () => {
    fetchSpy.mockImplementation(() =>
      Promise.resolve(
        new Response("Bad Request: invalid email", { status: 400 }),
      ),
    );

    const result = await sendEmail("bad-email", "Subject", "<p>Hi</p>");

    expect(result.success).toBe(false);
    expect(result.error).toContain("400");
  });
});

// ---------------------------------------------------------------------------
// sendBriefEmail tests
// ---------------------------------------------------------------------------

describe("sendBriefEmail", () => {
  let fetchSpy: ReturnType<typeof spyOn>;

  beforeEach(() => {
    currentConfig = { ...defaultConfig };
    fetchSpy = spyOn(globalThis, "fetch").mockImplementation(() =>
      Promise.resolve(
        new Response(JSON.stringify({ id: "brief-email-456" }), {
          status: 200,
        }),
      ),
    );
  });

  afterEach(() => {
    fetchSpy.mockRestore();
  });

  it("returns error when no EMAIL_TO configured", async () => {
    currentConfig = {
      ...defaultConfig,
      EMAIL_TO: undefined as unknown as string,
    };

    const result = await sendBriefEmail("Brief Title", "Brief content");

    expect(result.success).toBe(false);
    expect(result.error).toContain("EMAIL_TO");
  });

  it("calls sendEmail with HTML template containing title and content", async () => {
    const result = await sendBriefEmail(
      "Daily Brief",
      "## Summary\n\nAll is well.",
    );

    expect(result.success).toBe(true);
    expect(fetchSpy).toHaveBeenCalledTimes(1);

    const callArgs = fetchSpy.mock.calls[0];
    const body = JSON.parse(callArgs[1]?.body as string);

    // Should contain the HTML template with the brief title and content
    expect(body.html).toContain("Daily Brief");
    expect(body.html).toContain("<!DOCTYPE html>");
    expect(body.html).toContain("container");
    expect(body.subject).toBe("Daily Brief");
    expect(body.to).toEqual(["test@example.com"]);
  });
});

// ---------------------------------------------------------------------------
// sendAlertEmail tests
// ---------------------------------------------------------------------------

describe("sendAlertEmail", () => {
  let fetchSpy: ReturnType<typeof spyOn>;

  beforeEach(() => {
    currentConfig = { ...defaultConfig };
    fetchSpy = spyOn(globalThis, "fetch").mockImplementation(() =>
      Promise.resolve(
        new Response(JSON.stringify({ id: "alert-email-789" }), {
          status: 200,
        }),
      ),
    );
  });

  afterEach(() => {
    fetchSpy.mockRestore();
  });

  it("formats multiple alerts with urgency colors", async () => {
    const alerts: AlertEmailData[] = [
      {
        itemTitle: "Critical RCE in Apache",
        urgency: "critical",
        reason: "Active exploitation detected",
        recommendedAction: "Patch immediately",
        url: "https://example.com/advisory/1",
      },
      {
        itemTitle: "High Severity XSS",
        urgency: "high",
        reason: "Public exploit available",
        recommendedAction: "Update to latest version",
        url: null,
      },
    ];

    const result = await sendAlertEmail(alerts);

    expect(result.success).toBe(true);
    expect(fetchSpy).toHaveBeenCalledTimes(1);

    const callArgs = fetchSpy.mock.calls[0];
    const body = JSON.parse(callArgs[1]?.body as string);

    // Subject should reference alert count and first urgency
    expect(body.subject).toContain("[ALERT]");
    expect(body.subject).toContain("2 items");
    expect(body.subject).toContain("CRITICAL");

    // HTML body should contain both alerts
    expect(body.html).toContain("Critical RCE in Apache");
    expect(body.html).toContain("High Severity XSS");

    // Critical alert should have red border color
    expect(body.html).toContain("#dc2626");
    // High alert should have orange border color
    expect(body.html).toContain("#ea580c");

    // URL should be present for the first alert
    expect(body.html).toContain("https://example.com/advisory/1");
    expect(body.html).toContain("View source");
  });

  it("returns error when no EMAIL_TO configured", async () => {
    currentConfig = {
      ...defaultConfig,
      EMAIL_TO: undefined as unknown as string,
    };

    const alerts: AlertEmailData[] = [
      {
        itemTitle: "Test Alert",
        urgency: "medium",
        reason: "Test reason",
        recommendedAction: "Test action",
      },
    ];

    const result = await sendAlertEmail(alerts);

    expect(result.success).toBe(false);
    expect(result.error).toContain("EMAIL_TO");
  });
});
