// ---------------------------------------------------------------------------
// Email delivery via Resend API
// ---------------------------------------------------------------------------

import { getConfig } from "../config.ts";

// ---------------------------------------------------------------------------
// HTML template wrapper
// ---------------------------------------------------------------------------

export function wrapInHtmlTemplate(subject: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(subject)}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 700px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .container {
      background: #ffffff;
      border-radius: 8px;
      padding: 32px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }
    h1 { color: #111; font-size: 22px; margin-top: 0; }
    h2 { color: #333; font-size: 18px; border-bottom: 1px solid #eee; padding-bottom: 8px; }
    h3 { color: #555; font-size: 15px; }
    a { color: #2563eb; }
    pre {
      background: #f8f8f8;
      padding: 12px;
      border-radius: 4px;
      overflow-x: auto;
      font-size: 13px;
    }
    code { background: #f0f0f0; padding: 2px 5px; border-radius: 3px; font-size: 13px; }
    .footer {
      margin-top: 32px;
      padding-top: 16px;
      border-top: 1px solid #eee;
      font-size: 12px;
      color: #888;
    }
    .urgency-critical { color: #dc2626; font-weight: bold; }
    .urgency-high { color: #ea580c; font-weight: bold; }
    .urgency-medium { color: #ca8a04; }
    .urgency-low { color: #65a30d; }
  </style>
</head>
<body>
  <div class="container">
    ${body}
    <div class="footer">
      Generated by Coronagraph Intelligence Platform
    </div>
  </div>
</body>
</html>`;
}

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ---------------------------------------------------------------------------
// Simple markdown-to-HTML conversion for brief content
// ---------------------------------------------------------------------------

export function markdownToHtml(md: string): string {
  let html = escapeHtml(md);

  // Headers
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");

  // Bold and italic
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(.+?)\*/g, "<em>$1</em>");

  // Inline code
  html = html.replace(/`([^`]+)`/g, "<code>$1</code>");

  // Unordered lists (simple: lines starting with - )
  html = html.replace(/^- (.+)$/gm, "<li>$1</li>");
  // Wrap consecutive <li> in <ul>
  html = html.replace(/((?:<li>.*<\/li>\n?)+)/g, "<ul>$1</ul>");

  // Links
  html = html.replace(
    /\[([^\]]+)\]\(([^)]+)\)/g,
    '<a href="$2">$1</a>',
  );

  // Paragraphs: double newlines become paragraph breaks
  html = html.replace(/\n\n/g, "</p><p>");
  html = `<p>${html}</p>`;

  // Clean up empty paragraphs
  html = html.replace(/<p>\s*<\/p>/g, "");
  html = html.replace(/<p>(<h[123]>)/g, "$1");
  html = html.replace(/(<\/h[123]>)<\/p>/g, "$1");
  html = html.replace(/<p>(<ul>)/g, "$1");
  html = html.replace(/(<\/ul>)<\/p>/g, "$1");

  return html;
}

// ---------------------------------------------------------------------------
// Send email
// ---------------------------------------------------------------------------

export interface SendEmailResult {
  success: boolean;
  id?: string;
  error?: string;
}

export async function sendEmail(
  to: string,
  subject: string,
  htmlContent: string,
): Promise<SendEmailResult> {
  const config = getConfig();

  if (!config.RESEND_API_KEY) {
    console.log("[email] No RESEND_API_KEY configured, skipping email delivery");
    return { success: false, error: "RESEND_API_KEY not configured" };
  }

  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${config.RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Coronagraph <briefings@coronagraph.dev>",
        to: [to],
        subject,
        html: htmlContent,
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error(
        `[email] Resend API error: ${response.status} ${errorBody}`,
      );
      return {
        success: false,
        error: `Resend API returned ${response.status}: ${errorBody}`,
      };
    }

    const data = (await response.json()) as { id?: string };
    console.log(`[email] Email sent successfully: ${data.id}`);
    return { success: true, id: data.id };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[email] Failed to send email: ${message}`);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// Send a brief as a formatted email
// ---------------------------------------------------------------------------

export async function sendBriefEmail(
  title: string,
  content: string,
): Promise<SendEmailResult> {
  const config = getConfig();

  if (!config.EMAIL_TO) {
    console.log("[email] No EMAIL_TO configured, skipping");
    return { success: false, error: "EMAIL_TO not configured" };
  }

  const bodyHtml = `<h1>${escapeHtml(title)}</h1>\n${markdownToHtml(content)}`;
  const html = wrapInHtmlTemplate(title, bodyHtml);

  return sendEmail(config.EMAIL_TO, title, html);
}

// ---------------------------------------------------------------------------
// Send an alert as a formatted email
// ---------------------------------------------------------------------------

export interface AlertEmailData {
  itemTitle: string;
  urgency: string;
  reason: string;
  recommendedAction: string;
  url?: string | null;
}

export async function sendAlertEmail(
  alerts: AlertEmailData[],
): Promise<SendEmailResult> {
  const config = getConfig();

  if (!config.EMAIL_TO) {
    console.log("[email] No EMAIL_TO configured, skipping");
    return { success: false, error: "EMAIL_TO not configured" };
  }

  const subject = `[ALERT] ${alerts.length} item${alerts.length > 1 ? "s" : ""} flagged - ${alerts[0].urgency.toUpperCase()}`;

  const alertsHtml = alerts
    .map(
      (a) =>
        `<div style="margin-bottom: 20px; padding: 12px; border-left: 4px solid ${
          a.urgency === "critical"
            ? "#dc2626"
            : a.urgency === "high"
              ? "#ea580c"
              : "#ca8a04"
        }; background: #fafafa;">
        <h3 style="margin-top: 0;">
          <span class="urgency-${a.urgency}">[${a.urgency.toUpperCase()}]</span>
          ${escapeHtml(a.itemTitle)}
        </h3>
        <p><strong>Reason:</strong> ${escapeHtml(a.reason)}</p>
        <p><strong>Action:</strong> ${escapeHtml(a.recommendedAction)}</p>
        ${a.url ? `<p><a href="${escapeHtml(a.url)}">View source</a></p>` : ""}
      </div>`,
    )
    .join("\n");

  const bodyHtml = `<h1>Intelligence Alert</h1>\n${alertsHtml}`;
  const html = wrapInHtmlTemplate(subject, bodyHtml);

  return sendEmail(config.EMAIL_TO, subject, html);
}
